"use strict";
exports.__esModule = true;
var library_1 = require("./library");
var book_1 = require("./book");
var libro1 = new book_1.Book("La mosca", 200, "0-7645-2641-3", "Quijote", "editmala");
var libro2 = new book_1.Book("La mosca", 200, "0-7645-2641-3", "Manchado", "editmala");
var libro3 = new book_1.Book("La mosca", 200, "0-7645-2641-3", "Quijote", "editmala");
var libreria1 = new library_1.Library([libro1, libro2, libro3], "direccionLibreria", "pepito de los palotes");
console.log(libreria1.getNumberOfBooks());
console.log(libreria1.findByAuthor("Quijote"));
console.log("La dirección es: " + libreria1.getAddress());
console.log("El manager es: " + libreria1.getManager());
libreria1.setAddress("Avd Fuente");
libreria1.setManager("Ruiz");
console.log("La nueva dirección es: " + libreria1.getAddress());
console.log("El nuevo manager es: " + libreria1.getManager());
console.log(libreria1.toString());
